version: '3.7'

services:
  mysql:
    image: mysql:5.7
    container_name: mg-mysql
    ports:
      - "3306:3306"
    volumes:
      - magento-demo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: magento

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mg-pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  elasticsearch:
    image: elasticsearch:7.8.1
    container_name: mg-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node

  php:
    build: ./php
    container_name: mg-php
    volumes:
      - ~/Projects/mgtask/site:/var/www
    links:
      - mysql

  web:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ~/Projects/mgtask/site:/var/www
      - ./nginx/logs:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    container_name: mg-web
    links:
      - php

volumes:
  magento-demo-mysql-data:
